### ISSUE TITLE
Match error :system_limit

### ISSUE THREAD

**Issue by shankardevy** [cmullaparthi/ibrowse#135]
In my logs, I see a lot of error like this. I am using HTTPotion for get requests at the rate 3500/min approx. Is this a bug or can this be solved by changing any configuration?

```
** (exit) an exception was raised: ** (MatchError) no match of right hand side value: {:error, {:system_limit, [{:ets, :new, [:ibrowse_lb, [:public, :ordered_set]], []}, {:ibrowse_lb, :maybe_create_ets, 1, [file: 'src/ibrowse_lb.erl', line: 229]}, {:ibrowse_lb, :init, 1, [file: 'src/ibrowse_lb.erl', line: 77]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 306]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}} (ibrowse) src/ibrowse.erl:989: :ibrowse.do_get_connection/2 (ibrowse) src/ibrowse.erl:879: :ibrowse.handle_call/3 (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4 (stdlib) gen_server.erl:639: :gen_server.handle_msg/5 (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3 
=CRASH REPORT==== 15-Oct-2015::05:49:34 === crasher: initial call: ibrowse_lb:init/1 pid: <0.31909.0> registered_name: [] exception exit: {{badmatch, {error, {system_limit, [{ets,new, [ibrowse_lb,[public,ordered_set]], []}, {ibrowse_lb,maybe_create_ets,1, [{file,"src/ibrowse_lb.erl"}, {line,229}]}, {ibrowse_lb,init,1, [{file,"src/ibrowse_lb.erl"},{line,77}]}, {gen_server,init_it,6, [{file,"gen_server.erl"},{line,306}]}, {proc_lib,init_p_do_apply,3, [{file,"proc_lib.erl"},{line,237}]}]}}}, [{ibrowse,do_get_connection,2, [{file,"src/ibrowse.erl"},{line,989}]}, {ibrowse,handle_call,3, [{file,"src/ibrowse.erl"},{line,879}]}, {gen_server,try_handle_call,4, [{file,"gen_server.erl"},{line,607}]}, {gen_server,handle_msg,5, [{file,"gen_server.erl"},{line,639}]}, {proc_lib,init_p_do_apply,3, [{file,"proc_lib.erl"},{line,237}]}]} in function gen_server:terminate/7 (gen_server.erl, line 804) ancestors: [ibrowse,ibrowse_sup,<0.43.0>] messages: [] links: [] dictionary: [{my_trace_flag,false}, {ibrowse_trace_token,["LB: ","93.94.119.235",58,"84"]}] trap_exit: true status: running heap_size: 1598 stack_size: 27 reductions: 262 neighbours:
```

**Comment by cmullaparthi** [comment]
Can you describe a bit more please? Are you submitting requests to various
web servers from ibrowse? ibrowse creates one ETS table per server/port
combination you send requests to. These should get deleted after a period
of inactivity. So either there is a bug or you are making requests to many
different servers in a short space of time and you are hitting the default
erlang system limit of the number of ETS tables in the system.

**Comment by shankardevy** [comment]
@cmullaparthi that explains the issue. I am making requests to 3000+ different urls in a minute. So it's likely to hit the erlang's ets table limit of 1400. Is there a way to configure ibrowse to avoid this error or the only option is to increase the erlang table limit?

**Comment by eugenehp** [comment]
@shankardevy @marcoherbst @mosic @cmullaparthi

[ets official manual](http://www.erlang.org/doc/man/ets.html)

>The number of tables stored at one Erlang node is limited. The current default limit is approximately 1400 tables. The upper limit can be increased by setting the environment variable ERL_MAX_ETS_TABLES before starting the Erlang runtime system (i.e. with the -env option to erl/werl). The actual limit may be slightly higher than the one specified, but never lower.

**Comment by cmullaparthi** [comment]
I'm afraid increasing the number of ETS tables is the only option. ibrowse
needs on ETS table per endpoint to function.

**Comment by eugenehp** [comment]
@cmullaparthi thanks for the quick reply. Can you tell me please if you had a chance to run some kind of benchmark and compare ETS to another KV in ibrowse or elsewhere yet?

thanks :smile:

**Comment by cmullaparthi** [comment]
Not really Eugene. I've always tried to keep ibrowse 'dependency free' and
ETS is the only 'shared' data structure available out of the box with
Erlang. But if there is a shared data structure like ETS but with better
performance, I'm more than willing to try.

ETS is one of the fastest KV you can get for Erlang. It can be made faster
I think - there were a couple of research papers from Kostis' research
group highlighting bottlenecks within ETS. Hopefully the OTP team will
address them at some point.

Are you looking at this from a point of view of improving ibrowse
performance or generally looking for a better KV store in Erlang?

**Comment by eugenehp** [comment]
@cmullaparthi 
thanks for the quick reply :smile: 

Particularly the case that @shankardevy described is something I'm interested in.
First thing that came on my mind was some other KV driven database, like [Redis](https://github.com/artemeff/exredis) for example.

I understand your comment on the design, and totally agree on keeping it lean, is something that community wants.

On the other hand, if you maybe can point me to the part of the code, where is the abstraction level (wrapper) can be implemented to support different storages, that would be great. So if we might be able to create a PR it won't distract and ruin the design, but fit in it nicely :smile: 

let me know.

**Comment by cmullaparthi** [comment]
The main module to change is ibrowse_lb.erl - wherever you see ETS
operations.

The other module to change the ETS operations in ibrowse_http_client.erl,
in the functions
terminate/2
shutting_down/1
dec_pipeline_counter/1

That should do it I think. A previous pull request had isolated all these
into ibrowse_lb.erl, but for various reasons it didn't make it completely
into 'master'. A tidy up is needed methinks.

**Comment by eugenehp** [comment]
I see, thanks for the information @cmullaparthi I'll take a look, and let you know if I have any further questions.
Have a good day ahead!

**Comment by shankardevy** [comment]
thanks @cmullaparthi for taking time to answer all these questions. It's much appreciated. I am not still good at comprehending erlang but I will take a look at the files you mentioned. is it a good approach to use one ets table as kv for all requests irrespective of which server/port the url belong to? and are you interested in a PR in that case?

**Comment by cmullaparthi** [comment]
Hi Shankar,

Its worth a try, though some load testing will have to be done to gauge
impact. A PR would be nice, but please do consider testing for load to
multiple servers to see if there is a performance impact due to ETS locking
contention.
