### ISSUE TITLE
Socks5 not working for post requests?

### ISSUE THREAD

**Issue by vans163** [cmullaparthi/ibrowse#141]
The very last example which shows using socks5 with get request is not working, I am trying a post request and it is not using the proxy.

**Comment by cmullaparthi** [comment]
Are you using a SOCKS server and is it running when you invoke the request?

**Comment by vans163** [comment]
No im using a http server?? There is nothing in the code that makes it fall into the clause to use the socks5 proxy. If you pass it proxy_host it will fall into the clause to use HTTP proxy.

**Comment by cmullaparthi** [comment]
See https://github.com/cmullaparthi/ibrowse/blob/master/src/ibrowse_http_client.erl#L570 

Can you post the exact format of the request you are using please?

**Comment by vans163** [comment]
PostData = <<"igotsomestuff">>,
    PostUrl = "https://service.asite.com",
    Options =
                [
                {socks5_host, "1.1.1.1"},
                {socks5_port, 4444},
                {connect_timeout, 20000}, 
                {inactivity_timeout, 20000}
            ],
    {ok, "201", Headers, Body} = ibrowse:send_req(PostUrl, [], post, PostData, Options, 20000),

**Comment by cmullaparthi** [comment]
Just pushed a fix to master.

```
9> Options = [{socks5_host, "localhost"}, {socks5_port, 2001}].    
[{socks5_host,"localhost"},{socks5_port,2001}]

10> ibrowse:send_req("http://www.google.com", [], get, [], Options).
{ok,"302",
    [{"Cache-Control","private"},
     {"Content-Type","text/html; charset=UTF-8"},
     {"Location",
      "http://www.google.co.uk/?gfe_rd=cr&ei=iDyuVuy1BfLH8geBuaPwAg"},
     {"Content-Length","261"},
     {"Date","Sun, 31 Jan 2016 16:55:36 GMT"},
     {"Server","GFE/2.0"}],
    "<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF=\"http://www.google.co.uk/?gfe_rd=cr&amp;ei=iDyuVuy1BfLH8geBuaPwAg\">here</A>.\r\n</BODY></HTML>\r\n"}
```
