### ISSUE TITLE
missing EXIT handling in ibrowse_http_client.erl?

### ISSUE THREAD

**Issue by rnewson** [cmullaparthi/ibrowse#146]
Hi,

I'm trying to migrate couchdb 2.0 onto ibrowse 4.3 and am a bit stuck. Our test seems never to end now, and we have many messages of the form;

"Recvd unknown message {'EXIT',<0.15455.1>,normal} when in state:..."

The diff between the version we're using (a slightly custom one, you might recall we implemented SOCKS5 support independently) shows that ibrowse_http_client.erl is now trapping exits but appears not to have a clause to handle the EXIT message that it would receive by doing so.

locally, I can get our test suite to pass by adding;

```diff
diff --git a/src/ibrowse_http_client.erl b/src/ibrowse_http_client.erl
index b43b541..2c05262 100644
--- a/src/ibrowse_http_client.erl
+++ b/src/ibrowse_http_client.erl
@@ -295,6 +295,10 @@ handle_info({trace, Bool}, State) ->
 handle_info(delayed_stop, State) ->
    {stop, normal, State};

+handle_info({'EXIT', _Pid, Reason}, State) ->
+    {stop, Reason, State};
+
 handle_info(Info, State) ->
     io:format("Unknown message recvd for ~1000.p:~1000.p -> ~p~n",
               [State#state.host, State#state.port, Info]),
```

It's odd to trap exits but then ignore them so curious to hear your thoughts.

**Comment by cmullaparthi** [comment]
Hi Robert,

I'm not entirely sure where those EXIT messages are coming from, but if a gen_server is trapping exits, and the process exits _abnormally_, then the ```terminate``` callback gets invoked. You don't get a ```{'EXIT', pid(), normal}``` signal.

I can only think of a couple of possibilities of this happening.

1. You are using ```ibrowse:spawn_link_worker_process/1,2``` and the process making this call terminates before the HTTP connection handling process.

2. You are using a fun to generate the body of the HTTP request, and the fun is somehow creating a link to the HTTP client handling process. Could you please post the full trace message with the state? It might give some clues.

**Comment by rnewson** [comment]
Will post more tomorrow but, yes, the reason for exit is the atom normal in all the cases I see.

**Comment by rnewson** [comment]
I expanded the message in handle_info to include self();

Recvd unknown message {'EXIT',<0.17867.1>,normal} by <0.17849.1>

so ibrowse_http_client is receiving normal exit messages for other processes, as a consequence of now trapping exits. I think that points to an assumption elsewhere in couchdb that ibrowse did not trap exits. I think we'll have to defer the upgrade to 4.3 for the 2.0 release and come back to this, it might be a tricky fix.

I think, on the evidence so far, that it's not an ibrowse bug, but it might affect other users like it affects couchdb.

**Comment by cmullaparthi** [comment]
Okay, thanks for the clarification. I will close this for now, please reopen if you think it is an ibrowse bug after further investigation.
