### ISSUE TITLE
[Elixir] set `download_dir`

### ISSUE THREAD

**Issue by bmalum** [cmullaparthi/ibrowse#148]
Thanks for your work - it is the perfect fit for my Elixir Application. 

I'm wondering about something:

I want to use `ibrowse` from Elixir and also download a file. Now I have set the env var via 

`Application.put_env(:ibrowse, :download_dir, '/Users/bMalum/Downloads')`
`Application.put_env(:ibrowse, 'download_dir', '/Users/bMalum/Downloads')`

The file was still created in the working directory ... how can I change it from Elixir?

**Comment by cmullaparthi** [comment]
You're welcome :-)

Can you specify how exactly you are invoking ibrowse:send_req ?

**Comment by bmalum** [comment]
`{:ok, status, headers, body} = :ibrowse.send_req(url, [{:cookie, cookie}], :get, [], [{:save_response_to_file, filename}])
`

url = CharList URL 
Cookie = 'login=somesecret'

**Comment by cmullaparthi** [comment]
Hmm... looks like ibrowse only saves in the specified download directory only if you haven't specified a filename. If you specify a filename, it assumes it is the full path. 

If you really want to do both, the workaround is to ensure that ```filename``` is a filename with either an absolute or relative path.

**Comment by bmalum** [comment]
Ahhh! I will try 😊 update in a few minutes

**Comment by bmalum** [comment]
Works! 👍  I think it would be nice to find this again in the Docs 😊 

Awesome - OpenSource and super fast Response! So happy right now

I <3 the Erlang/Elixir community!

**Comment by cmullaparthi** [comment]
Glad to be of service :-)
