### ISSUE TITLE
4.3 Package Release for Hex

### ISSUE THREAD

**Issue by marcelog** [cmullaparthi/ibrowse#152]
Hello!

The last published hex package version is [4.2.2](https://hex.pm/packages/ibrowse/4.2.2). It would be great to have 4.3 published as well. Are you planning on publishing it too?

Thanks in advance!

Best,

**Comment by cmullaparthi** [comment]
Yes, will do, thanks for the reminder.

**Comment by cmullaparthi** [comment]
I've published 4.4.0 including all commits since version 4.3. I hope this is ok. Let me know if you need 4.3 published.

**Comment by marcelog** [comment]
That's perfect, thank you very much @cmullaparthi. 

Best regards,
