### ISSUE TITLE
deploy version 4.4.2 into hex.pm

### ISSUE THREAD

**Issue by TheSquad** [cmullaparthi/ibrowse#167]
Right now 4.4.1 has a bug concerning ipv6 that is fixed by 4.4.2.
However, only 4.4.1 is deployed on hex.pm, so sub-dependencies of HTTPoison will download the 4.4.1.

**Comment by mandersondesign** [comment]
I hit this issue myself. It was fixed by forcing v4.4.0. Would love to have 4.4.2 available!

**Comment by yordis** [comment]
I am wondering if the issue we are facing in Tesla is related to this issue: https://github.com/elixir-tesla/tesla/pull/589

Update: Confirmed it fixes the issue!

**Comment by yordis** [comment]
@cmullaparthi is there any opportunity of deprecating `4.4.1` and release `4.4.2`?

**Comment by cmullaparthi** [comment]
Hi @yordis sure thing, I'll get this done within the next day or so.

**Comment by cmullaparthi** [comment]
Done. https://hex.pm/packages/ibrowse/4.4.2
