### ISSUE TITLE
Error : IBrowse request "couldn't create CL_HTML"

### ISSUE THREAD

**Issue by Kanz1A** [cmullaparthi/ibrowse#176]
Sorry,

Ive got the "Ibrowse request" 
Couldn't create CL_HTML

can anyone tell me how to solve the Problem?

System:
A2000 Pistorm
OS 3.2.1
MUI 3.8
IBrowse 2.5.5

**Comment by cmullaparthi** [comment]
Sorry, you've got the wrong ibrowse. This is a HTTP client to be used in erlang applications. You seem to want support for the IBrowse browser on an Amiga?

**Comment by Kanz1A** [comment]
Oh yes Sorry
