### ISSUE TITLE
Receiving unexpected message from ibrowse process

### ISSUE THREAD

**Issue by alexeyr** [cmullaparthi/ibrowse#36]
When I call 

```
ibrowse:send_req(Url, [], get, [], 
             [{save_response_to_file,
                  "/mware/working_dir/media/video/7eb8971f-0527-4c6c-af93-11aa0afb0c1a.avi"},
              {socket_options,[{keepalive,true}]},
              {inactivity_timeout,180000},
              {connect_timeout,180000}])
```

and the request times out, it returns `{error,req_timedout}`. But then the process which called `send_req` _also_ receives a message `{#Ref<0.0.0.821>,{error,req_timedout}}`, which is not expected, since there is no `{stream_to, self()}` option.

**Comment by parubets** [comment]
got same problem with receiving random messages to my process after request was finished... i'm using Elixir and latest version of HTTPotion (based on ibrowse)

**Comment by cmullaparthi** [comment]
Can you send some traces please?

**Comment by unrealhoang** [comment]
I'm from Elixir using HTTPotion and having the same problem.
My call was:
```
    response = HTTPotion.get state.url, state.options
```
when I disconnecting from network to test request failure, my GenServer receiving unexpected message as below
```
SimpleRest.handle_info({#Reference<0.0.3.144>, {:error, {:conn_failed, {:error, :timeout}}}}
```

**Comment by cmullaparthi** [comment]
Sorry about the delay in responding, summer holidays and all that.

Can you please specify what options you are invoking the request with?

**Comment by unrealhoang** [comment]
No worry, I temporarily fixed the problem by catching unexpected message.
About options, my `state.options` is either empty `[]` or `[headers: ["User-Agent": "ApiClient"]]`
